## Анализ массива данных

In [1]:
import numpy as np
import pandas as pd
import matplotlib

In [2]:
df = pd.read_csv('dataset_Facebook.csv', sep=';')

### Статистика по всему массиву

In [45]:
df

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100
1,139441,Status,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164
2,139441,Photo,3,12,3,3,0.0,2413,4373,177,113,154,2812,1503,132,0,66.0,14.0,80
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393
5,139441,Status,2,12,1,9,0.0,10472,20849,1191,1073,1389,16034,7852,1016,1,152.0,33.0,186
6,139441,Photo,3,12,1,3,1.0,11692,19479,481,265,364,15432,9328,379,3,249.0,27.0,279
7,139441,Photo,3,12,7,9,1.0,13720,24137,537,232,305,19728,11056,422,0,325.0,14.0,339
8,139441,Status,2,12,7,3,0.0,11844,22538,1530,1407,1692,15220,7912,1250,0,161.0,31.0,192
9,139441,Photo,3,12,6,10,0.0,4694,8668,280,183,250,4309,2324,199,3,113.0,26.0,142
10,139441,Status,2,12,5,10,0.0,21744,42334,4258,4100,4540,37849,18952,3798,0,233.0,19.0,252
11,139441,Photo,2,12,5,10,0.0,3112,5590,208,127,145,3887,2174,165,0,88.0,18.0,106
12,139441,Photo,2,12,5,10,0.0,2847,5133,193,115,133,3779,2072,152,0,90.0,14.0,104
13,139441,Photo,2,12,5,3,0.0,2549,4896,249,134,168,3631,1917,183,5,137.0,10.0,152
14,138414,Photo,2,12,4,5,1.0,22784,39941,887,337,417,34415,19312,684,2,577.0,20.0,599
15,138414,Status,2,12,3,10,0.0,10060,19680,1264,1209,1425,17272,8548,1162,4,86.0,18.0,108
16,138414,Photo,3,12,3,3,0.0,1722,2981,163,123,148,1868,1050,123,2,40.0,12.0,54
17,138414,Photo,1,12,2,12,1.0,53264,111785,1706,1103,1655,92512,39776,1307,15,678.0,20.0,713
18,138414,Status,3,12,2,3,0.0,3930,7509,130,86,112,5009,2410,101,4,54.0,17.0,75
19,138414,Photo,3,12,1,11,0.0,1591,2825,121,88,111,2116,1161,100,0,34.0,8.0,42
20,138414,Photo,2,12,1,3,0.0,2848,5066,200,142,184,3561,1963,157,3,66.0,12.0,81
21,138414,Photo,1,12,7,10,0.0,1384,2467,15,15,20,2196,1172,15,0,0.0,0.0,0
22,138414,Link,1,12,7,10,0.0,3454,6853,118,104,130,6282,3100,106,0,16.0,2.0,18
23,138414,Photo,3,12,7,3,0.0,2723,4888,176,118,143,2964,1621,143,0,72.0,24.0,96
24,138414,Status,2,12,6,10,0.0,8488,15294,1341,1270,1489,9684,5244,995,3,99.0,19.0,121
25,138458,Status,2,12,6,3,0.0,8284,15104,1521,1462,1711,10266,5372,1200,0,88.0,18.0,106
26,138458,Status,2,12,5,11,0.0,19552,34143,2806,2531,3420,17748,9824,1779,10,412.0,72.0,494
27,138458,Photo,3,12,5,3,0.0,2478,4306,212,124,149,2612,1443,166,0,100.0,17.0,117
28,138895,Photo,2,12,5,3,0.0,9560,18264,973,559,885,9217,4748,621,36,523.0,63.0,622
29,138895,Video,1,12,4,11,1.0,36208,61262,1141,1068,1728,30131,14112,559,18,143.0,13.0,174
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
470,91437,Link,1,2,3,13,0.0,9356,14986,448,381,505,13919,8460,392,4,114.0,13.0,131
471,91330,Photo,3,2,3,3,0.0,7732,13264,1066,1002,1336,8753,4880,570,7,160.0,57.0,224
472,91223,Photo,1,2,2,13,0.0,5240,8893,857,837,1020,7420,4232,466,0,46.0,15.0,61
473,91116,Photo,3,2,2,4,1.0,7132,12060,1004,944,1226,8294,4736,576,4,136.0,42.0,182
474,91009,Photo,1,2,1,12,0.0,21928,39641,1512,1479,1837,6338,3672,497,0,73.0,13.0,86
475,86909,Photo,3,1,6,16,1.0,5754,9238,1179,1143,1452,6101,3546,420,0,65.0,19.0,84
476,86909,Photo,1,1,6,10,1.0,37088,10966,2728,2288,3183,66311,34352,2021,7,579.0,47.0,633
477,86909,Link,1,1,6,4,0.0,39600,7927,572,496,581,12522,8176,167,1,101.0,5.0,107
478,86909,Photo,3,1,5,13,0.0,5536,8745,1141,1099,1461,5225,3098,483,1,74.0,31.0,106
479,86909,Photo,3,1,5,4,0.0,6056,10325,1117,1078,1427,6823,3788,487,7,84.0,36.0,127
480,86909,Photo,2,1,4,11,0.0,11484,20696,1762,1635,2741,8774,5124,722,56,360.0,99.0,515
481,86491,Link,1,1,4,4,1.0,4938,7910,66,63,70,6625,3804,59,0,5.0,2.0,7
482,86491,Photo,3,1,3,10,0.0,66784,9456,2969,2833,3645,17809,11328,801,3,187.0,36.0,226
483,86491,Photo,2,1,3,3,0.0,5526,8779,1096,1058,1399,5732,3412,453,2,69.0,26.0,97
484,86491,Photo,3,1,2,7,0.0,5040,8367,1062,1023,1348,5485,3068,437,2,82.0,24.0,108
485,86491,Link,1,1,2,2,0.0,5168,8371,66,59,71,7041,3996,58,0,12.0,2.0,14
486,85979,Photo,3,1,1,12,0.0,5034,8030,1020,993,1243,5340,3094,440,2,56.0,25.0,83
487,85979,Photo,3,1,1,2,0.0,4908,7491,957,937,1153,4642,2842,393,1,44.0,21.0,66
488,85979,Photo,3,1,7,10,0.0,9700,17442,1407,1271,2007,8872,4876,660,21,277.0,80.0,378
489,85979,Photo,3,1,7,2,0.0,4800,7754,975,938,1278,4932,2820,432,1,74.0,28.0,103
490,85979,Photo,3,1,6,11,0.0,5280,8703,951,911,1237,5757,3300,431,1,79.0,30.0,110
491,85979,Photo,3,1,6,3,1.0,6184,10228,956,901,1140,6085,3502,437,1,105.0,46.0,152
492,85979,Link,1,1,5,11,0.0,45920,5808,753,655,763,15766,10720,220,0,128.0,9.0,137
493,85093,Photo,3,1,1,2,0.0,8412,13960,1179,1111,1632,8632,5348,699,17,185.0,55.0,257
494,85093,Photo,3,1,7,10,0.0,5400,9218,810,756,1003,5654,3230,422,10,125.0,41.0,176
495,85093,Photo,3,1,7,2,0.0,4684,7536,733,708,985,4750,2876,392,5,53.0,26.0,84
496,81370,Photo,2,1,5,8,0.0,3480,6229,537,508,687,3961,2104,301,0,53.0,22.0,75
497,81370,Photo,1,1,5,2,0.0,3778,7216,625,572,795,4742,2388,363,4,93.0,18.0,115
498,81370,Photo,3,1,4,11,0.0,4156,7564,626,574,832,4534,2452,370,7,91.0,38.0,136
499,81370,Photo,2,1,4,4,NaN,4188,7292,564,524,743,3861,2200,316,0,91.0,28.0,119

In [28]:
df.describe()

,Page total likes,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
count,500.000000,500.000000,500.000000,500.000000,500.000000,499.000000,500.00000,5.000000e+02,500.000000,500.000000,500.000000,5.000000e+02,500.000000,500.000000,500.00000,499.000000,496.000000,500.000000
mean,123194.176000,1.880000,7.038000,4.150000,7.840000,0.278557,13903.36000,2.958595e+04,920.344000,798.772000,1415.130000,1.676638e+04,6585.488000,609.986000,7.48200,177.945892,27.266129,212.120000
std,16272.813214,0.852675,3.307936,2.030701,4.368589,0.448739,22740.78789,7.680325e+04,985.016636,882.505013,2000.594118,5.979102e+04,7682.009405,612.725618,21.18091,323.398742,42.613292,380.233118
min,81370.000000,1.000000,1.000000,1.000000,1.000000,0.000000,238.00000,5.700000e+02,9.000000,9.000000,9.000000,5.670000e+02,236.000000,9.000000,0.00000,0.000000,0.000000,0.000000
25%,112676.000000,1.000000,4.000000,2.000000,3.000000,0.000000,3315.00000,5.694750e+03,393.750000,332.500000,509.250000,3.969750e+03,2181.500000,291.000000,1.00000,56.500000,10.000000,71.000000
50%,129600.000000,2.000000,7.000000,4.000000,9.000000,0.000000,5281.00000,9.051000e+03,625.500000,551.500000,851.000000,6.255500e+03,3417.000000,412.000000,3.00000,101.000000,19.000000,123.500000
75%,136393.000000,3.000000,10.000000,6.000000,11.000000,1.000000,13168.00000,2.208550e+04,1062.000000,955.500000,1463.000000,1.486050e+04,7989.000000,656.250000,7.00000,187.500000,32.250000,228.500000
max,139441.000000,3.000000,12.000000,7.000000,23.000000,1.000000,180480.00000,1.110282e+06,11452.000000,11328.000000,19779.000000,1.107833e+06,51456.000000,4376.000000,372.00000,5172.000000,790.000000,6334.000000

Заметим, что столбцы Paid, like, chare содержат пропущенные значения (общее число записей меньше 500). Такие данные портят статистику. Следует либо удалить соответствующие записи(строки), либо заполнить их с помощью средних значений. Поскольку изначальных данных не так много, выберем второй способ.

In [51]:
df = df.fillna(df.median(axis=0), axis=0)

И еще раз посмотрим статискику по всему массиву данных, уже без пропущенных значений.

In [52]:
df.describe()

,Page total likes,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
count,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.00000,5.000000e+02,500.000000,500.000000,500.000000,5.000000e+02,500.000000,500.000000,500.00000,500.000000,500.000000,500.000000
mean,123194.176000,1.880000,7.038000,4.150000,7.840000,0.278000,13903.36000,2.958595e+04,920.344000,798.772000,1415.130000,1.676638e+04,6585.488000,609.986000,7.48200,177.792000,27.200000,212.120000
std,16272.813214,0.852675,3.307936,2.030701,4.368589,0.448462,22740.78789,7.680325e+04,985.016636,882.505013,2000.594118,5.979102e+04,7682.009405,612.725618,21.18091,323.092858,42.448554,380.233118
min,81370.000000,1.000000,1.000000,1.000000,1.000000,0.000000,238.00000,5.700000e+02,9.000000,9.000000,9.000000,5.670000e+02,236.000000,9.000000,0.00000,0.000000,0.000000,0.000000
25%,112676.000000,1.000000,4.000000,2.000000,3.000000,0.000000,3315.00000,5.694750e+03,393.750000,332.500000,509.250000,3.969750e+03,2181.500000,291.000000,1.00000,56.750000,10.000000,71.000000
50%,129600.000000,2.000000,7.000000,4.000000,9.000000,0.000000,5281.00000,9.051000e+03,625.500000,551.500000,851.000000,6.255500e+03,3417.000000,412.000000,3.00000,101.000000,19.000000,123.500000
75%,136393.000000,3.000000,10.000000,6.000000,11.000000,1.000000,13168.00000,2.208550e+04,1062.000000,955.500000,1463.000000,1.486050e+04,7989.000000,656.250000,7.00000,187.250000,32.000000,228.500000
max,139441.000000,3.000000,12.000000,7.000000,23.000000,1.000000,180480.00000,1.110282e+06,11452.000000,11328.000000,19779.000000,1.107833e+06,51456.000000,4376.000000,372.00000,5172.000000,790.000000,6334.000000

Видим, что есть объект с максимальным значением лайков - 5172, число которых значительно превосходит среднее значение - 178.

In [54]:
df.loc[df['like']== 5172]

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
244,130791,Photo,2,7,3,5,1.0,180480,319133,8072,4010,6242,108752,51456,3316,372,5172.0,790.0,6334

Это тот же объект, которому принадлежит рекорд по share, total interaction. Его и стоит назвать **самым популярным** объектом в выборке.

### Статистика в разрезе типов контента

In [55]:
print (df['Type'].unique()) #уникальные виды контента

['Photo' 'Status' 'Link' 'Video']

In [56]:
df.loc[df['Type']== 'Photo'].describe()

,Page total likes,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
count,426.000000,426.000000,426.000000,426.000000,426.000000,426.000000,426.000000,4.260000e+02,426.000000,426.000000,426.000000,4.260000e+02,426.000000,426.000000,426.000000,426.000000,426.000000,426.000000
mean,122354.171362,1.917840,6.805164,4.107981,7.997653,0.279343,13137.814554,2.899450e+04,818.946009,690.431925,1299.025822,1.642248e+04,6059.103286,507.305164,7.492958,182.420188,27.082160,216.579812
std,16324.528694,0.884007,3.234676,2.056286,4.413082,0.449204,22877.787010,8.095792e+04,868.447092,731.712670,1965.996628,6.450149e+04,7819.018244,399.972665,22.522275,344.861492,44.714733,405.709232
min,81370.000000,1.000000,1.000000,1.000000,1.000000,0.000000,238.000000,5.700000e+02,9.000000,9.000000,9.000000,5.670000e+02,236.000000,9.000000,0.000000,0.000000,0.000000,0.000000
25%,109670.000000,1.000000,4.000000,2.000000,3.000000,0.000000,3092.500000,5.390000e+03,399.000000,335.000000,513.000000,3.695250e+03,2100.250000,300.250000,1.000000,57.000000,10.000000,71.250000
50%,128032.000000,2.000000,7.000000,4.000000,9.000000,0.000000,4675.000000,8.118500e+03,605.500000,528.500000,827.000000,5.498000e+03,3110.000000,403.000000,3.000000,100.500000,19.000000,122.000000
75%,136013.000000,3.000000,10.000000,6.000000,11.000000,1.000000,10571.000000,1.701375e+04,949.000000,832.250000,1327.500000,9.823000e+03,5577.000000,569.750000,7.000000,186.000000,32.000000,225.000000
max,139441.000000,3.000000,12.000000,7.000000,23.000000,1.000000,180480.000000,1.110282e+06,11452.000000,11328.000000,19779.000000,1.107833e+06,51456.000000,3430.000000,372.000000,5172.000000,790.000000,6334.000000

In [57]:
df.loc[df['Type']== 'Status'].describe()

,Page total likes,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
count,45.000000,45.000000,45.000000,45.000000,45.000000,45.000000,45.000000,45.000000,45.000000,45.000000,45.000000,45.000000,45.000000,45.000000,45.000000,45.000000,45.000000,45.000000
mean,132647.044444,2.022222,9.066667,4.577778,7.244444,0.222222,13078.888889,24244.466667,2040.222222,1949.555556,2838.866667,18664.266667,9908.577778,1719.844444,8.911111,176.711111,31.422222,217.044444
std,7902.145290,0.398228,2.553073,1.924588,3.926342,0.420437,5218.086371,9929.142874,1351.996838,1319.980433,2075.419548,7521.069017,3997.608572,1083.684581,12.451400,150.772499,24.272589,178.479940
min,104070.000000,1.000000,3.000000,1.000000,2.000000,0.000000,3930.000000,7509.000000,128.000000,86.000000,112.000000,5009.000000,2410.000000,101.000000,0.000000,13.000000,1.000000,17.000000
25%,131300.000000,2.000000,7.000000,3.000000,3.000000,0.000000,9232.000000,17099.000000,1151.000000,1073.000000,1512.000000,13887.000000,7360.000000,995.000000,2.000000,86.000000,16.000000,106.000000
50%,135713.000000,2.000000,10.000000,5.000000,9.000000,0.000000,11096.000000,20849.000000,1701.000000,1599.000000,2201.000000,17502.000000,8980.000000,1604.000000,4.000000,150.000000,28.000000,186.000000
75%,138353.000000,2.000000,12.000000,6.000000,10.000000,0.000000,15816.000000,30514.000000,2675.000000,2567.000000,3420.000000,22103.000000,11792.000000,2256.000000,10.000000,226.000000,39.000000,265.000000
max,139441.000000,3.000000,12.000000,7.000000,15.000000,1.000000,31136.000000,59964.000000,6164.000000,5934.000000,9237.000000,37849.000000,21352.000000,4376.000000,60.000000,859.000000,123.000000,1009.000000

In [58]:
df.loc[df['Type']== 'Link'].describe()

,Page total likes,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
count,22.000000,22.000000,22.000000,22.000000,22.000000,22.000000,22.000000,22.000000,22.000000,22.000000,22.000000,22.000000,22.000000,22.000000,22.000000,22.000000,22.000000,22.000000
mean,116363.181818,1.136364,6.590909,4.272727,5.727273,0.272727,18544.590909,28725.454545,342.818182,292.681818,374.090909,11148.590909,6544.363636,210.545455,2.818182,73.318182,12.909091,89.045455
std,21459.767350,0.467563,4.563406,1.856310,3.930126,0.455842,21399.411331,50042.047711,340.174414,291.385261,358.404787,8888.568907,5960.612461,188.873030,3.633657,85.746240,11.751025,95.720564
min,85979.000000,1.000000,1.000000,1.000000,2.000000,0.000000,1536.000000,3094.000000,24.000000,23.000000,26.000000,2307.000000,1180.000000,19.000000,0.000000,5.000000,0.000000,6.000000
25%,98829.250000,1.000000,3.000000,3.000000,3.000000,0.000000,3878.000000,6861.500000,105.000000,84.750000,120.000000,6367.750000,3156.000000,92.250000,0.000000,19.500000,5.500000,32.750000
50%,115396.000000,1.000000,4.500000,4.500000,4.000000,0.000000,7422.000000,9773.000000,244.000000,205.000000,290.000000,9034.500000,5039.000000,161.500000,1.500000,37.000000,10.500000,52.500000
75%,138059.000000,1.000000,11.750000,6.000000,9.250000,0.750000,30938.000000,26153.750000,422.000000,355.750000,472.750000,13903.750000,8140.000000,251.750000,4.000000,110.750000,15.000000,125.000000
max,138895.000000,3.000000,12.000000,7.000000,14.000000,1.000000,70912.000000,229733.000000,1374.000000,1106.000000,1345.000000,42338.000000,27232.000000,788.000000,15.000000,379.000000,44.000000,420.000000

In [60]:
df.loc[df['Type']== 'Video'].describe()

,Page total likes,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
count,7.000000,7.0,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.00000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000
mean,135014.857143,1.0,9.571429,3.571429,8.714286,0.571429,51205.714286,102622.428571,1707.00000,1584.714286,2600.142857,43149.857143,17386.285714,979.428571,12.285714,231.428571,52.142857,295.857143
std,4730.551709,0.0,2.299068,1.511858,4.347961,0.534522,48825.191031,101838.314111,1174.78608,1160.701471,2296.643524,31072.683306,9861.583607,650.805362,8.693183,142.025652,42.643595,183.992236
min,126424.000000,1.0,6.000000,2.000000,2.000000,0.000000,13544.000000,30235.000000,459.00000,411.000000,539.000000,21436.000000,9568.000000,363.000000,2.000000,65.000000,13.000000,81.000000
25%,132835.000000,1.0,8.000000,2.500000,6.500000,0.000000,19144.000000,36181.500000,829.00000,763.000000,1197.500000,25644.500000,12340.000000,503.000000,4.000000,121.000000,13.500000,144.000000
50%,137893.000000,1.0,11.000000,3.000000,11.000000,1.000000,30624.000000,56950.000000,1779.00000,1643.000000,2331.000000,30131.000000,14112.000000,885.000000,17.000000,204.000000,44.000000,271.000000
75%,138111.000000,1.0,11.000000,4.500000,11.000000,1.000000,68488.000000,140854.500000,2090.50000,1845.500000,2804.500000,45845.500000,17312.000000,1192.000000,18.000000,330.000000,80.000000,440.500000
max,138895.000000,1.0,12.000000,6.000000,13.000000,1.000000,139008.000000,277100.000000,3872.00000,3822.000000,7327.000000,107502.000000,38720.000000,2218.000000,23.000000,449.000000,121.000000,550.000000